--- #YAML:1.0
name:                GD-Graph-Cartesian
version:             0.07
abstract:            Make cartesian graph using GD package
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    GD:                            2.02
    List::MoreUtils:               0
    List::Util:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
